[database]
host = localhost
user = user
password = password
db_name = msearch
# PostgreSQL 
db_type = postgresql
db_name = msearch
port = 5432

# db_type = mysql
# port = 3306

# SQLite configuration
# db_type = sqlite
# db_name = msearch.db

[model]
llm_model = cn-clip
default_model = ViT-B-16

[logging]
level = INFO
file = logs/msearch.log

[api]
base_url = http://localhost:5000
timeout = 30

[tmp]
tmp = ./tmp
cache = ./cache

[Milvus]
host = localhost
port = 19530

[General]
num_threads = 4
max_mermory = 4G
#搜索返回数量
default_key=100

target_folder = /data  # 本地目标文件夹
#nfs
nfs_folder = /mnt/nfs/data  # NFS目标文件夹
#webdav
webdav_url = http://192.168.1.100:8080/webdav  # WebDAV地址
webdav_username = admin  # WebDAV用户名
webdav_password = admin  # WebDAV密码
