[database]
host = localhost
user = user
password = password
<<<<<<< HEAD
db_name = msearch
=======

>>>>>>> 4bc4798 (Initial commit)
# PostgreSQL 
db_type = postgresql
db_name = msearch
port = 5432

# db_type = mysql
# port = 3306

# SQLite configuration
# db_type = sqlite
# db_name = msearch.db

[model]
llm_model = cn-clip
default_model = ViT-B-16

[logging]
level = INFO
<<<<<<< HEAD
file = logs/msearch.log
=======
file = logs/app.log
>>>>>>> 4bc4798 (Initial commit)

[api]
base_url = http://localhost:5000
timeout = 30

<<<<<<< HEAD
[cache]
cache_dir= ./cache
=======
[tmp]
tmp = ./tmp
cache = ./cache
>>>>>>> 4bc4798 (Initial commit)

[Milvus]
host = localhost
port = 19530

[General]
num_threads = 4
max_mermory = 4G
#搜索返回数量
default_key=100

<<<<<<< HEAD
target_folder = /data  # 本地目标文件夹
#nfs
nfs_folder = /mnt/nfs/data  # NFS目标文件夹
#webdav
webdav_url = http://192.168.1.100:8080/webdav  # WebDAV地址
webdav_username = admin  # WebDAV用户名
webdav_password = admin  # WebDAV密码
=======
>>>>>>> 4bc4798 (Initial commit)
