name: Code Quality and Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # 每周日午夜运行一次完整扫描

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
    
    - name: Run bandit security scan
      run: |
        bandit -r src -f json -o bandit-results.json || true
    
    - name: Run safety check
      run: |
        safety check --full-report || true

  code-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install analysis tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint mypy
    
    - name: Run flake8 with extended checks
      run: |
        flake8 src tests --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
    
    - name: Run pylint
      run: |
        pylint --disable=R,C,W src || true
    
    - name: Run mypy type checking
      run: |
        mypy --ignore-missing-imports --follow-imports=skip src

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Dependency Review
      uses: actions/dependency-review-action@v3